# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "qme8AVaIZCtBRCpJQeUQmnhyaSWW+YIlP7LOHPWZ9s03BJGiJu4YpuwtXA6eg7iH44hAlSGGU8GslRE50o6PHpoHd0IrKzEVsto3JBzRjUHWNmjE+/M6YxkycNiRIX+Oi8lQ3fd12jiDrp+dn7fJJrhPJrGMvd3KoLbjc/0BADb7G5N1ppNlyDgjQycUzcCmV0mnQ8AouxDqTjoKqe4gjOhONWw1tyL65/BTToyaRQToZDypHNuZQj7hTKSLaI6+F05cZ3xNnRlD2ZkvfHs27ovpGineMEVU+r1S1+XqttToyOuwclVakswBdR0IA8yTxIFR6HkNAi/h5Hjo9o74gANGj6l+iwtArTpxchxC8cQiwIiEn+NJsagjVjQIXoXkPQU09UhmNgMgWH9oeJaayCW86pac8kiF5kZHBZnO5DZJGHfHKrL/+eKkDej0oOjGcy9gzbd4MFojd43VigVXdxKIoHp1/fp/+eYRSBSOVwGDnVHUIK/CynZinOytXy/OATqO7kBcG09jLrjs57q5Wj57L9JcvOYCtjVjl26FR+LA1FAc4O2VVre+D02qnVF3M+O4rnAqHhQ8MqeiotY6ffcLrUO8gIkxrPMMtDmHLe+1lmb8bO65QN47Y1r/FjVnSqDGfaZX8EWbE4bKvmcPkDuzeFvVeSMzdfAjIBmkwtg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
