travis:
  secure:
    BINSTAR_TOKEN: Vz1aiyT++EbMExv6kKenNa0b4HMZgP2umxtQdJn9FMWMPJaDWR2ytCMFMovim4wIPOONLipJ2SrwDvMyKSy6PdGUpQawbI+9m3n3F4MMqxBT1ebafi4cWVBPcdWDSitjyKVgWrJSG42vWZ0aDvTcgyhE0vizq5mUEAk8AHHCIc4AJtEQBJYRqCBf1mJlzBHf7zXsrzkIhX7muu5sJkKDrzw6tiXyRooQX1LCnGCmxdyFrbXD41HxLxcjZGulgKlAWq1aaekDfMS6wASRGIFYHUzactGGXLoO8NGTjyXY5hSSDerbDUWr0Xot6amElcMSCopFBw6u2Vj67S+FtVe3ENcBc/xDwUZQEuf37b+EAHS7x20WFh3MOBGi5r3wslqm0lZ+HLCe9YHVjh0RJo8Gd7XooJnDiIBfE7u1iiUynz67DuFm4EwER4gOGHff7uvrXKy5VgUh8flElGi4911aiYNXFiqYa75U0DBRq6JH64JMC8U9C7AqsS/o6KFH8byZ+5snVWBX1mYsUQJYPlCuoARpVCTjKTiulpO0GO5Ep7TcJBoloCnrZ1JqYYVXJlAhQZL94qj61s2v1aYqWxQAqWkJWc48WM4LIzGXSk87jubCH3v5ai/nzIdFRalUTbUHmwEMtUD9U5jrNY0wALG8tmXa3hkwS39V9GE3sqAfD4I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
