travis:
  secure:
    BINSTAR_TOKEN: qme8AVaIZCtBRCpJQeUQmnhyaSWW+YIlP7LOHPWZ9s03BJGiJu4YpuwtXA6eg7iH44hAlSGGU8GslRE50o6PHpoHd0IrKzEVsto3JBzRjUHWNmjE+/M6YxkycNiRIX+Oi8lQ3fd12jiDrp+dn7fJJrhPJrGMvd3KoLbjc/0BADb7G5N1ppNlyDgjQycUzcCmV0mnQ8AouxDqTjoKqe4gjOhONWw1tyL65/BTToyaRQToZDypHNuZQj7hTKSLaI6+F05cZ3xNnRlD2ZkvfHs27ovpGineMEVU+r1S1+XqttToyOuwclVakswBdR0IA8yTxIFR6HkNAi/h5Hjo9o74gANGj6l+iwtArTpxchxC8cQiwIiEn+NJsagjVjQIXoXkPQU09UhmNgMgWH9oeJaayCW86pac8kiF5kZHBZnO5DZJGHfHKrL/+eKkDej0oOjGcy9gzbd4MFojd43VigVXdxKIoHp1/fp/+eYRSBSOVwGDnVHUIK/CynZinOytXy/OATqO7kBcG09jLrjs57q5Wj57L9JcvOYCtjVjl26FR+LA1FAc4O2VVre+D02qnVF3M+O4rnAqHhQ8MqeiotY6ffcLrUO8gIkxrPMMtDmHLe+1lmb8bO65QN47Y1r/FjVnSqDGfaZX8EWbE4bKvmcPkDuzeFvVeSMzdfAjIBmkwtg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
